#!/bin/bash
set -e

# Encrypt the clipboard
message=$(pbpaste | gpg --pinentry-mode loopback --clearsign $*)

# Store the signed message in clipboard
echo "$message" | pbcopy

echo "Signed to clipboard!"
