#!/bin/bash
set -e

# Encrypt the clipboard
message=$(pbpaste | gpg --pinentry-mode loopback --decrypt)

# Store the encrypted message in clipboard
echo "$message" | pbcopy

echo "Decrypted to clipboard!"
