#!/bin/bash
set -e

# Required for the pinentry
export GPG_TTY=$(tty)

# Encrypt the clipboard
message=$(pbpaste | gpg --decrypt)

# Store the encrypted message in clipboard
echo "$message" | pbcopy

echo "Decrypted to clipboard!"
