#!/bin/bash
set -e

if [ -z "$*" ]; then
	echo "Enter recipient email address:"
	read recipient
else
	recipient="$1"
	# Remove recipient from the list of args
	shift
fi

# Look for the recipient in our key ring
# or search for the user if not found
if ! gpg --list-keys | grep --quiet "$recipient"; then
	gpg --keyserver hkps://pgp.mit.edu --search-keys "$recipient"
fi

# Encrypt the file to clipboard
gpg --sign --encrypt --recipient "$recipient" $*
