#!/bin/bash
set -e

if [ -z "$*" ]; then
	echo "Enter recipient email address:"
	read recipient
else
	recipient="$1"
	# Remove recipient from the list of args
	shift
fi

# Look for the recipient in our key ring
# or search for the user if not found
if ! gpg --list-keys | grep --quiet "$recipient"; then
	gpg --keyserver hkps://pgp.mit.edu --search-keys "$recipient"
fi

# Encrypt the clipboard
message=$(pbpaste | gpg --pinentry-mode loopback --sign --encrypt --armor --recipient "$recipient" $*)

# Store the encrypted message in clipboard
echo "$message" | pbcopy

echo "Encrypted to clipboard!"
